### ISSUE TITLE
Does celo safe support submitting batch txs?

### ISSUE THREAD

**Issue by clemsos** [celo-org/safe-transaction-service#81]
I am trying to submit an array of txs to the service - which works well on safe global. I am getting an `Unexpected delegate call` error on the UI (see screenshot below). Also the `Interact with:` address appears to be wrong. Is it just a UI glitch? 

many thanks !

![Screenshot 2023-04-13 at 16 22 39](https://user-images.githubusercontent.com/743246/231789945-92409fab-d75b-4d95-b783-c46100f92f5f.png)

NB: I submitted it directly using a script at the following tx service address http://mainnet-tx-svc.celo-safe-prod.celo-networks-dev.org/ . Submitting a single tx works fine

**Comment by arthurgousset** [comment]
Hey Clément👋 Thanks for your message! 

We're currently working closely with Safe Global to add native support for Celo. 
You should see more in the next 1-2 weeks. Please hang tight! 

This post might help you stay in the loop re native Safe support: [[Multisig] Celo Safe (re)launch](https://forum.celo.org/t/multisig-celo-safe-re-launch/4529/53?u=0xarthurxyz)

Since we’re working with the Safe Global team regarding support in the official [app.safe.global](http://app.safe.global) UI, I’m hesitant to commit to fixing the above issue at this point. Sorry!

Hope that makes sense :)
